AWSTemplateFormatVersion: '2010-09-09'
Description: Application Load Balancer público con Target Group y Listener

Resources:
  MinticALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: MinticALB
      Subnets:
        - !ImportValue Mintic-SubnetPublic1
        - !ImportValue Mintic-SubnetPublic2
      SecurityGroups:
        - !ImportValue Mintic-SecurityGroupId
      Scheme: internet-facing
      Type: application

  MinticTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !ImportValue Mintic-VPCId
      Protocol: HTTP
      Port: 80
      TargetType: instance
      HealthCheckPath: /

  MinticListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref MinticALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref MinticTargetGroup

Outputs:
  MinticALBDNS:
    Description: DNS del Application Load Balancer
    Value: !GetAtt MinticALB.DNSName
    Export:
      Name: MinticALBDNS

  MinticTargetGroupArn:
    Description: ARN del Target Group
    Value: !Ref MinticTargetGroup
    Export:
      Name: MinticTargetGroupArn
